-- MySQL Script generated by MySQL Workbench
-- Fri Dec  9 17:38:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agbank
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agbank` ;

-- -----------------------------------------------------
-- Schema agbank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agbank` DEFAULT CHARACTER SET utf8 ;
USE `agbank` ;

-- -----------------------------------------------------
-- Table `agbank`.`Agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agbank`.`Agencia` (
  `IdAgencia` INT NOT NULL,
  `NomeAgencia` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(150) NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`IdAgencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agbank`.`ContaCorrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agbank`.`ContaCorrente` (
  `IdContaCorrente` INT NOT NULL,
  `IdAgencia` INT NOT NULL,
  `ContaCorrenteAgencia` VARCHAR(7) NOT NULL,
  `ContaCorrenteNumero` VARCHAR(10) NOT NULL,
  `ContaCorrenteSaldo` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`IdContaCorrente`, `IdAgencia`),
  INDEX `fk_ContaCorrente_Agencia1_idx` (`IdAgencia` ASC),
  CONSTRAINT `fk_ContaCorrente_Agencia1`
    FOREIGN KEY (`IdAgencia`)
    REFERENCES `agbank`.`Agencia` (`IdAgencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agbank`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agbank`.`Cliente` (
  `IdCliente` INT NOT NULL,
  `ClienteNome` VARCHAR(80) NOT NULL,
  `ClienteCPF` VARCHAR(20) NOT NULL,
  `ClienteFone` VARCHAR(20) NULL,
  `IdContaCorrente` INT NOT NULL,
  `IdAgencia` INT NOT NULL,
  PRIMARY KEY (`IdCliente`, `IdContaCorrente`, `IdAgencia`),
  INDEX `fk_Cliente_ContaCorrente1_idx` (`IdContaCorrente` ASC, `IdAgencia` ASC),
  CONSTRAINT `fk_Cliente_ContaCorrente1`
    FOREIGN KEY (`IdContaCorrente` , `IdAgencia`)
    REFERENCES `agbank`.`ContaCorrente` (`IdContaCorrente` , `IdAgencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agbank`.`Extrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agbank`.`Extrato` (
  `IdExtrato` INT NOT NULL,
  `IdContaCorrente` INT NOT NULL,
  `DataMovimento` DATETIME NOT NULL,
  `Operacao` VARCHAR(10) NOT NULL,
  `ValorOperacao` DECIMAL(17,2) NOT NULL,
  PRIMARY KEY (`IdExtrato`),
  INDEX `fk_Extrato_ContaCorrente1_idx` (`IdContaCorrente` ASC) ,
  CONSTRAINT `fk_Extrato_ContaCorrente1`
    FOREIGN KEY (`IdContaCorrente`)
    REFERENCES `agbank`.`ContaCorrente` (`IdContaCorrente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
